import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BarChart3, House, PackageCheck, RefreshCw, Smartphone, Sparkles } from "lucide-react";
import { Navigation } from "@/components/navigation";

const steps = [
  "Add the branded NFC unit to the order",
  "Customer places it on the fridge",
  "The brand stays visible in daily routines",
  "Customer taps with a phone",
  "The selected brand experience opens",
  "The interaction becomes measurable",
];

export default function Homepage() {
  return (
    <main className="fc-home">
      <style>{`
        .fc-home{--paper:#f5f0e8;--cream:#ebe2d5;--ink:#1b211b;--muted:#686d64;--green:#173d30;--green2:#285744;--line:rgba(27,33,27,.14);background:var(--paper);color:var(--ink);font-family:var(--font-plus-jakarta),Arial,sans-serif;line-height:1.55;overflow:hidden}
        .fc-home *{box-sizing:border-box}.fc-home a{color:inherit;text-decoration:none}.fc-wrap{width:min(1320px,calc(100% - 96px));margin:auto}
        .fc-brand{display:flex;align-items:center;gap:11px;font-weight:700;letter-spacing:-.04em;font-size:19px}.fc-brand img{width:30px;height:30px}
        .fc-hero{position:relative;min-height:690px;padding:78px 0 68px;display:grid;grid-template-columns:1fr;align-items:center}.fc-hero-copy{position:relative;z-index:2;padding-bottom:20px}.fc-kicker{font:600 11px/1.2 ui-monospace,monospace;letter-spacing:.16em;text-transform:uppercase;color:var(--green2);display:flex;align-items:center;gap:10px}.fc-kicker:before{content:"";width:24px;height:1px;background:currentColor}.fc-hero h1{font:400 clamp(58px,7.6vw,104px)/.92 Georgia,serif;letter-spacing:-.055em;max-width:740px;margin:0 0 24px}.fc-hero h1 em{color:var(--green2);font-weight:400}.fc-hero-copy>p{font-size:17px;color:#555c53;max-width:530px;line-height:1.75;margin:0}.fc-main-cta{margin-top:32px;display:inline-flex;align-items:center;gap:14px;background:var(--green);color:white!important;padding:15px 21px;border-radius:99px;font-size:14px;font-weight:600;transition:transform .2s,background .2s}.fc-main-cta:hover{transform:translateY(-2px);background:#24523e}
        .fc-statement{padding:96px 0 106px;background:var(--green);color:#f8f4ec}.fc-statement-inner{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:start}.fc-overline{font:11px ui-monospace,monospace;letter-spacing:.15em;text-transform:uppercase;color:#b3c4ad}.fc-statement h2{font:400 clamp(42px,6vw,76px)/1 Georgia,serif;letter-spacing:-.04em;margin:0;max-width:850px}.fc-statement p{font-size:16px;line-height:1.8;color:#d2dbd2;max-width:660px;margin:24px 0 0}.fc-metrics{padding:82px 0 96px}.fc-section-heading{display:flex;justify-content:space-between;align-items:end;gap:36px;margin-bottom:44px}.fc-section-heading h2{font:400 clamp(42px,5.4vw,70px)/.98 Georgia,serif;letter-spacing:-.045em;margin:15px 0 0;max-width:720px}.fc-section-heading>p{max-width:320px;color:var(--muted);font-size:14px;line-height:1.7;margin:0}.fc-metric-grid{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.fc-metric{padding:30px 30px 34px 0;min-height:278px;border-right:1px solid var(--line)}.fc-metric+.fc-metric{padding-left:30px}.fc-metric:last-child{border-right:0}.fc-metric-icon{width:42px;height:42px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;color:var(--green)}.fc-metric-icon svg{width:18px}.fc-metric h3{font:400 28px/1.1 Georgia,serif;letter-spacing:-.025em;margin:26px 0 12px}.fc-metric p{font-size:14px;line-height:1.75;color:var(--muted);margin:0;max-width:360px}
        .fc-how{padding:92px 0 102px;background:#eae3d7}.fc-how-grid{display:grid;grid-template-columns:.86fr 1.14fr;gap:90px;align-items:start}.fc-how-copy{position:sticky;top:40px}.fc-how-copy h2{font:400 clamp(46px,5.6vw,72px)/.96 Georgia,serif;letter-spacing:-.045em;margin:17px 0}.fc-how-copy p{font-size:15px;line-height:1.8;color:var(--muted);max-width:410px}.fc-how-art{height:300px;margin-top:38px;overflow:hidden;border-radius:180px 180px 8px 8px}.fc-how-art img{width:100%;height:100%;object-fit:cover}.fc-steps{list-style:none;margin:0;padding:0;border-top:1px solid var(--line)}.fc-steps li{display:grid;grid-template-columns:54px 1fr 20px;gap:18px;align-items:center;min-height:78px;border-bottom:1px solid var(--line);font-size:14px}.fc-steps li>span:first-child{font:11px ui-monospace,monospace;color:#85877d}.fc-steps li svg{width:16px;color:var(--green2)}
        .fc-measure{padding:98px 0 104px}.fc-measure-top{display:grid;grid-template-columns:1fr 1fr;gap:75px;align-items:end}.fc-measure h2{font:400 clamp(45px,5.7vw,74px)/.97 Georgia,serif;letter-spacing:-.045em;margin:15px 0 0}.fc-measure-top p{color:var(--muted);font-size:15px;line-height:1.8;max-width:540px;margin:0 0 5px}.fc-measure-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:52px}.fc-measure-card{background:#ece6dc;padding:25px;min-height:210px;display:flex;flex-direction:column}.fc-measure-card svg{width:20px;color:var(--green2)}.fc-measure-card h3{font:400 24px Georgia,serif;margin:28px 0 9px}.fc-measure-card p{font-size:13px;line-height:1.7;color:var(--muted);margin:0}
        .fc-home .daily-moments{padding:104px 0 120px;background:var(--cream);color:var(--ink);overflow:hidden}.fc-home .daily-moments-head{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:56px;align-items:end;margin-bottom:54px}.fc-home .daily-moments h2{font:400 clamp(50px,6.4vw,88px)/.94 Georgia,serif;letter-spacing:-.04em;margin:0;max-width:13ch}.fc-home .daily-moments h2 em{font-weight:400;color:var(--green2)}.fc-home .daily-moments-intro{font-size:16px;line-height:1.7;color:#555c53;max-width:42ch;margin:0}.fc-home .daily-moments-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));grid-template-rows:repeat(2,minmax(290px,31vw));gap:14px}.fc-home .daily-moment{position:relative;margin:0;overflow:hidden;background:#2b2824;isolation:isolate}.fc-home .daily-moment:nth-child(1){grid-column:span 7}.fc-home .daily-moment:nth-child(2){grid-column:span 5}.fc-home .daily-moment:nth-child(3),.fc-home .daily-moment:nth-child(4){grid-column:span 6}.fc-home .daily-moment img{width:100%;height:100%;object-fit:cover;filter:saturate(.86) contrast(.97);transition:transform .8s cubic-bezier(.22,1,.36,1),filter .4s ease}.fc-home .daily-moment:hover img{transform:scale(1.045);filter:saturate(1) contrast(1)}.fc-home .daily-moment:after{content:"";position:absolute;inset:0;z-index:1;background:linear-gradient(180deg,rgba(0,0,0,.02) 38%,rgba(0,0,0,.78) 100%);pointer-events:none}.fc-home .daily-moment figcaption{position:absolute;z-index:2;left:0;right:0;bottom:0;display:flex;align-items:flex-end;justify-content:space-between;gap:20px;padding:24px 26px}.fc-home .daily-moment-title{font-size:clamp(18px,1.6vw,24px);font-weight:600;line-height:1.15;max-width:18ch;color:#fff}.fc-home .daily-moment-number{font:11px ui-monospace,monospace;letter-spacing:.08em;color:#e8c99c;white-space:nowrap}
        .fc-paths{padding:100px 0 104px;background:#f8f5ee}.fc-paths-head{text-align:center;max-width:760px;margin:0 auto 44px}.fc-paths h2{font:400 clamp(44px,5.5vw,70px)/.98 Georgia,serif;letter-spacing:-.04em;margin:16px 0}.fc-paths-head p{color:var(--muted);font-size:15px}.fc-path-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;text-align:left}.fc-path{position:relative;background:var(--green);color:#f8f5ee;padding:34px;min-height:260px;display:flex;flex-direction:column;justify-content:space-between;transition:transform .25s,background .25s}.fc-path:hover{transform:translateY(-4px);background:#234b38}.fc-path:nth-child(2){background:#d9e1d6;color:var(--ink)}.fc-path:nth-child(2):hover{background:#cbd8ca}.fc-path:first-child,.fc-path:first-child *{color:#fff}.fc-path:first-child small{opacity:.78}.fc-path:first-child p{opacity:.86}.fc-path small{font:11px ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase;opacity:.7}.fc-path h3{font:400 38px Georgia,serif;margin:25px 0 8px}.fc-path p{font-size:14px;max-width:440px;opacity:.76;margin:0}.fc-path>svg{position:absolute;right:30px;top:30px;width:22px}.fc-footer{padding:26px 0 32px;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;font-size:12px;color:var(--muted)}.fc-footer-links{display:flex;gap:24px}.fc-footer a:hover{color:var(--green)}
        @media(max-width:800px){.fc-wrap{width:min(100% - 42px,650px)}.fc-hero{grid-template-columns:1fr;padding:63px 0 50px;gap:34px}.fc-hero h1{font-size:clamp(56px,13vw,88px)}.fc-statement{padding:70px 0}.fc-statement-inner,.fc-how-grid,.fc-measure-top{grid-template-columns:1fr;gap:26px}.fc-statement h2{font-size:54px}.fc-section-heading{display:block}.fc-section-heading>p{margin-top:18px}.fc-metric-grid{grid-template-columns:1fr}.fc-metric,.fc-metric+.fc-metric{min-height:0;padding:24px 0 27px;border-right:0;border-bottom:1px solid var(--line)}.fc-metric:last-child{border-bottom:0}.fc-metric h3{margin-top:18px}.fc-how{padding:70px 0}.fc-how-copy{position:static}.fc-how-art{height:250px;margin-top:24px}.fc-measure,.fc-paths{padding:72px 0}.fc-measure-cards{grid-template-columns:1fr;margin-top:32px}.fc-measure-card{min-height:175px}.fc-measure-card h3{margin-top:19px}.fc-home .daily-moments{padding:76px 0 80px}.fc-home .daily-moments-head{grid-template-columns:1fr;gap:22px;margin-bottom:34px}.fc-home .daily-moments h2{font-size:clamp(48px,14vw,68px)}.fc-home .daily-moments-grid{display:flex;gap:14px;overflow-x:auto;margin:0 -21px;padding:0 21px 12px;scroll-snap-type:x mandatory}.fc-home .daily-moment{flex:0 0 84vw;height:470px;scroll-snap-align:center}.fc-home .daily-moment figcaption{padding:22px}.fc-path-grid{grid-template-columns:1fr}.fc-path{min-height:220px;padding:26px}.fc-path h3{font-size:33px}.fc-footer{align-items:flex-start;gap:20px;flex-direction:column}.fc-footer-links{gap:20px}}
        @media(prefers-reduced-motion:reduce){.fc-home *{scroll-behavior:auto!important;transition:none!important}}
      `}</style>
      <Navigation />
      <div className="fc-wrap">
        <section className="fc-hero" id="home">
          <div className="fc-hero-copy"><h1>Turn every delivered order into <em>next purchase.</em></h1><p>Fridge Channel puts your brand on the fridge door—visible throughout everyday household routines and ready to bring customers back with one tap.</p><a className="fc-main-cta" href="#solutions">Find the right FC solution <ArrowRight size={16} /></a></div>
        </section>
      </div>
      <section className="fc-statement"><div className="fc-wrap fc-statement-inner"><div className="fc-overline">Stay present after delivery</div><div><h2>A brand presence that lives beyond the box.</h2><p>FC turns each equipped order into a persistent, brand-controlled household touchpoint. It keeps the brand visible after the original purchase and creates a direct path from the customer&apos;s home to the brand&apos;s next selected experience.</p></div></div></section>
      <section className="fc-metrics"><div className="fc-wrap"><div className="fc-section-heading"><div><div className="fc-kicker">Built for everyday recall</div><h2>Show up where the next decision happens.</h2></div><p>A small physical touchpoint can keep your brand close through the routines that shape what households buy next.</p></div><div className="fc-metric-grid">
        <article className="fc-metric"><div className="fc-metric-icon"><House /></div><h3>10+ daily family impressions</h3><p>Repeated home routines create an always-on brand surface, keeping visibility alive long after a purchase, campaign, or email send is over.</p></article>
        <article className="fc-metric"><div className="fc-metric-icon"><Sparkles /></div><h3>No algorithm. No ad blockers.</h3><p>No algorithm decides who sees your brand. No ad budget keeps the light on. FC is hardware-owned presence—inside the customer&apos;s home, under your control.</p></article>
        <article className="fc-metric"><div className="fc-metric-icon"><Smartphone /></div><h3>One tap → Next Order</h3><p>Bring customers back to your selected destination when they are ready to replenish—reducing search and shortening the path to purchase.</p></article>
      </div></div></section>
      <section className="fc-how" id="how-it-works"><div className="fc-wrap fc-how-grid"><div className="fc-how-copy"><div className="fc-kicker">From package to presence</div><h2>You put it in the box. We build the channel.</h2><p>FC designs and manufactures the branded NFC unit, prepares the digital destination, and delivers it ready to include with participating orders.</p><div className="fc-how-art"><Image src="/dtc/3dtcbrandcafe- magnet1.jpeg" alt="Branded NFC touchpoint displayed on a refrigerator" width={1000} height={700} /></div></div><ol className="fc-steps">{steps.map((step,index)=><li key={step}><span>{String(index+1).padStart(2,"0")}</span><span>{step}</span><ArrowRight /></li>)}</ol></div></section>
      <section className="fc-measure"><div className="fc-wrap"><div className="fc-measure-top"><div><div className="fc-kicker">Learn from every interaction</div><h2>Every tap creates a measurable signal.</h2></div><p>Measure the journey from tap to landing-page visit and onward action. With a clear value exchange and customer consent, the same touchpoint can collect feedback, preferences, replenishment needs, and other zero-party data—helping improve the next experience.</p></div><div className="fc-measure-cards"><article className="fc-measure-card"><BarChart3 /><h3>Understand the journey</h3><p>See engagement from tap through the selected destination and onward action.</p></article><article className="fc-measure-card"><RefreshCw /><h3>Keep the experience current</h3><p>Update the digital destination remotely as products, campaigns, and customer needs change.</p></article><article className="fc-measure-card"><PackageCheck /><h3>Learn with permission</h3><p>Invite customers to share preferences and needs with a clear value exchange and their consent.</p></article></div></div></section>
      <section className="daily-moments"><div className="fc-wrap"><div className="daily-moments-head"><div><h2>Routine moments. <em>One lasting presence.</em></h2></div><p className="daily-moments-intro">Fridge Channel lives where daily decisions already happen — naturally visible from the first coffee through the final kitchen reset.</p></div><div className="daily-moments-grid">
        <figure className="daily-moment"><img src="/UseScenes/01.png" alt="Morning coffee being prepared in a bright kitchen" /><figcaption><span className="daily-moment-title">Morning coffee preparation</span><span className="daily-moment-number">01 / 04</span></figcaption></figure>
        <figure className="daily-moment"><img src="/UseScenes/02.png" alt="A customer visiting the fridge during breakfast" /><figcaption><span className="daily-moment-title">Breakfast fridge visits</span><span className="daily-moment-number">02 / 04</span></figcaption></figure>
        <figure className="daily-moment"><img src="/UseScenes/03.png" alt="A customer using Fridge Channel while preparing a meal" /><figcaption><span className="daily-moment-title">Cooking and meal prep</span><span className="daily-moment-number">03 / 04</span></figcaption></figure>
        <figure className="daily-moment"><img src="/UseScenes/05.png" alt="A tidy kitchen and fridge after the meal" /><figcaption><span className="daily-moment-title">Post-meal cleanup and kitchen reset</span><span className="daily-moment-number">04 / 04</span></figcaption></figure>
      </div></div></section>
      <section className="fc-paths" id="solutions"><div className="fc-wrap"><div className="fc-paths-head"><div className="fc-kicker" style={{justifyContent:"center"}}>One physical channel</div><h2>Choose the path that fits your business.</h2><p>Start with the Fridge Channel solution designed for your sales model.</p></div><div className="fc-path-grid"><Link className="fc-path" href="/who-we-serve/dtcbrands"><small>For direct-to-consumer</small><div><h3>FC for DTC Brands</h3><p>Bring customers from the home back to your brand&apos;s next experience.</p></div><ArrowUpRight /></Link><Link className="fc-path" href="/asin-plus"><small>For Amazon brands</small><div><h3>FC ASIN+</h3><p>Create a persistent home touchpoint that can guide customers to what&apos;s next.</p></div><ArrowUpRight /></Link></div></div></section>
      <footer className="fc-wrap fc-footer"><Link href="/" className="fc-brand"><Image src="/icon.svg" alt="" width={24} height={24} /><span>Fridge Channel</span></Link><div className="fc-footer-links"><Link href="/contact">Contact</Link><Link href="/trust">Trust Center</Link></div><span>© Fridge Channel</span></footer>
    </main>
  );
}
