import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Pin } from "lucide-react";
import { Navigation } from "@/components/navigation";
import { CreativeDirection } from "@/components/creative-direction";
import { ImagePlaceholder } from "@/components/image-placeholder";

const steps = [
  { number: "01", title: "Add the branded NFC unit to the order" },
  { number: "02", title: "Customer places it on the fridge" },
  { number: "04", title: "CTAs back to your site: reorder, subscribe, bundle, loyalty, referral, quiz." },
  { number: "03", title: "The brand stays visible in daily routines" },
];

export default function Homepage() {
  return (
    <main className="fc-home creative-inc-theme">
      <style>{`
        .fc-home{--paper:#f5f0e8;--cream:#ebe2d5;--ink:#1b211b;--muted:#686d64;--green:#173d30;--green2:#285744;--line:rgba(27,33,27,.14);background:var(--paper);color:var(--ink);font-family:var(--font-plus-jakarta),Arial,sans-serif;line-height:1.55;overflow:hidden}
        .fc-home *{box-sizing:border-box}.fc-home a{color:inherit;text-decoration:none}.fc-wrap{width:min(1320px,calc(100% - 96px));margin:auto}
        .fc-brand{display:flex;align-items:center;gap:11px;font-weight:700;letter-spacing:-.04em;font-size:19px}.fc-brand img{width:30px;height:30px}
        .fc-hero{position:relative;min-height:690px;padding:78px 0 68px;display:grid;grid-template-columns:1fr;align-items:center}.fc-hero-copy{position:relative;z-index:2;padding-bottom:20px}.fc-kicker{font:600 11px/1.2 ui-monospace,monospace;letter-spacing:.16em;text-transform:uppercase;color:var(--green2);display:flex;align-items:center;gap:10px}.fc-kicker:before{content:"";width:24px;height:1px;background:currentColor}.fc-hero h1{font:400 clamp(58px,7.6vw,104px)/.92 Georgia,serif;letter-spacing:-.055em;max-width:1480px;margin:0 0 24px}.fc-hero h1 em{color:var(--green2);font-weight:400}.fc-hero-copy>p{font-size:17px;color:#555c53;max-width:530px;line-height:1.75;margin:0}.fc-main-cta{margin-top:32px;display:inline-flex;align-items:center;gap:14px;background:var(--green);color:white!important;padding:15px 21px;border-radius:99px;font-size:14px;font-weight:600;transition:transform .2s,background .2s}.fc-main-cta:hover{transform:translateY(-2px);background:#24523e}
        .fc-statement{padding:96px 0 106px;background:var(--green);color:#f8f4ec}.fc-statement-inner{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:start}.fc-overline{font:11px ui-monospace,monospace;letter-spacing:.15em;text-transform:uppercase;color:#b3c4ad}.fc-statement h2{font:400 clamp(42px,6vw,76px)/1 Georgia,serif;letter-spacing:-.04em;margin:0;max-width:850px}.fc-statement p{font-size:16px;line-height:1.8;color:#d2dbd2;max-width:660px;margin:24px 0 0}.fc-metrics{padding:82px 0 96px}.fc-metric-grid{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.fc-metric{padding:30px 30px 34px 0;min-height:278px;border-right:1px solid var(--line)}.fc-metric+.fc-metric{padding-left:30px}.fc-metric:last-child{border-right:0}.fc-metric-icon{width:42px;height:42px;border:1px solid var(--line);border-radius:50%;display:grid;place-items:center;color:var(--green)}.fc-metric-icon svg{width:18px}.fc-metric h3{font:400 28px/1.1 Georgia,serif;letter-spacing:-.025em;margin:26px 0 12px}.fc-metric p{font-size:14px;line-height:1.75;color:var(--muted);margin:0;max-width:360px}
        .fc-how{padding:92px 0 102px;background:#eae3d7}.fc-how-grid{display:grid;grid-template-columns:.72fr 1.28fr;gap:70px;align-items:start}.fc-how-copy{padding-top:18px}.fc-how-copy h2{font:400 clamp(52px,6.4vw,88px)/.94 Georgia,serif;letter-spacing:-.045em;margin:0;max-width:8ch}.fc-step-cards{position:relative;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:48px 52px;padding:30px 34px 38px}.fc-step-path{position:absolute;z-index:0;inset:0;width:100%;height:100%;pointer-events:none;overflow:visible}.fc-step-path path{fill:none;stroke:var(--green2);stroke-width:2;stroke-dasharray:8 7;stroke-linecap:round;opacity:.7;animation:fc-step-dash 3s linear infinite}@keyframes fc-step-dash{to{stroke-dashoffset:-30}}.fc-steps{list-style:none;margin:0;padding:0;display:contents}.fc-steps li{position:relative;z-index:1;display:flex;flex-direction:column;min-height:230px;padding:22px 20px;background:#fff;border:1px solid rgba(27,33,27,.08);border-radius:25px;box-shadow:0 10px 20px rgba(27,33,27,.14);font-size:14px;transition:transform .3s,box-shadow .3s}.fc-steps li:hover{z-index:3;transform:scale(1.04) rotate(0deg);box-shadow:0 18px 28px rgba(27,33,27,.18)}.fc-steps li:nth-child(3n+1){transform:rotate(3deg)}.fc-steps li:nth-child(3n+2){transform:rotate(-3deg)}.fc-steps li:nth-child(3n){transform:rotate(2deg)}.fc-steps li:nth-child(3n+1):hover,.fc-steps li:nth-child(3n+2):hover,.fc-steps li:nth-child(3n):hover{transform:scale(1.04) rotate(0deg)}.fc-steps li:before{content:"";position:absolute;inset:58px 18px 18px;border-radius:15px;background:#eff6ff;border:1px solid #dbeafe;z-index:-1}.fc-steps li:nth-child(3n+1):before{background:#fff7ed;border-color:#ffedd5}.fc-steps li:nth-child(3n):before{background:#faf5ff;border-color:#f3e8ff}.fc-steps li svg:first-child{width:30px;height:30px;margin:0 auto 16px;color:#2563eb}.fc-steps li:nth-child(3n+1) svg:first-child{color:#f97316}.fc-steps li:nth-child(3n) svg:first-child{color:#9333ea}.fc-steps li>span:first-of-type{font:28px/1 "Comic Sans MS","Chalkboard SE",sans-serif;margin:0 0 16px;color:#2563eb}.fc-steps li:nth-child(3n+1)>span:first-of-type{color:#f97316}.fc-steps li:nth-child(3n)>span:first-of-type{color:#9333ea}.fc-steps li>span:nth-of-type(2){display:block;color:#20251f;font-size:18px;font-weight:600;line-height:1.25}.fc-steps li>svg:last-child{display:none}
        .fc-home .fc-hero-media video{display:block;width:100%;height:100%;object-fit:cover}.fc-home .daily-moments{padding:104px 0 120px;background:var(--cream);color:var(--ink);overflow:hidden}.fc-home .daily-moments-head{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:56px;align-items:end;margin-bottom:54px}.fc-home .daily-moments h2{font:400 clamp(50px,6.4vw,88px)/.94 Georgia,serif;letter-spacing:-.04em;margin:0;max-width:13ch}.fc-home .daily-moments h2 em{font-weight:400;color:var(--green2)}.fc-home .daily-moments-intro{font-size:16px;line-height:1.7;color:#555c53;max-width:42ch;margin:0}.fc-home .daily-moments-grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));grid-template-rows:repeat(2,minmax(290px,31vw));gap:14px}.fc-home .daily-moment{position:relative;margin:0;overflow:hidden;background:#2b2824;isolation:isolate}.fc-home .daily-moment:nth-child(1){grid-column:span 7}.fc-home .daily-moment:nth-child(2){grid-column:span 5}.fc-home .daily-moment:nth-child(3),.fc-home .daily-moment:nth-child(4){grid-column:span 6}.fc-home .daily-moment img{width:100%;height:100%;object-fit:cover;filter:saturate(.86) contrast(.97);transition:transform .8s cubic-bezier(.22,1,.36,1),filter .4s ease}.fc-home .daily-moment:hover img{transform:scale(1.045);filter:saturate(1) contrast(1)}.fc-home .daily-moment:after{content:"";position:absolute;inset:0;z-index:1;background:linear-gradient(180deg,rgba(0,0,0,.02) 38%,rgba(0,0,0,.78) 100%);pointer-events:none}.fc-home .daily-moment figcaption{position:absolute;z-index:2;left:0;right:0;bottom:0;display:flex;align-items:flex-end;justify-content:space-between;gap:20px;padding:24px 26px}.fc-home .daily-moment-title{font-size:clamp(18px,1.6vw,24px);font-weight:600;line-height:1.15;max-width:18ch;color:#fff}.fc-home .daily-moment-number{font:11px ui-monospace,monospace;letter-spacing:.08em;color:#e8c99c;white-space:nowrap}
        .fc-paths{padding:100px 0 104px;background:#f8f5ee}.fc-paths-head{text-align:center;max-width:760px;margin:0 auto 44px}.fc-paths h2{font:400 clamp(44px,5.5vw,70px)/.98 Georgia,serif;letter-spacing:-.04em;margin:16px 0}.fc-paths-head p{color:var(--muted);font-size:15px}.fc-path-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;text-align:left}.fc-path{position:relative;background:var(--green);color:#f8f5ee;padding:34px;min-height:260px;display:flex;flex-direction:column;justify-content:space-between;transition:transform .25s,background .25s}.fc-path:hover{transform:translateY(-4px);background:#234b38}.fc-path:nth-child(2){background:#d9e1d6;color:var(--ink)}.fc-path:nth-child(2):hover{background:#cbd8ca}.fc-path:first-child,.fc-path:first-child *{color:#fff}.fc-path:first-child small{opacity:.78}.fc-path:first-child p{opacity:.86}.fc-path small{font:11px ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase;opacity:.7}.fc-path h3{font:400 38px Georgia,serif;margin:25px 0 8px}.fc-path p{font-size:14px;max-width:440px;opacity:.76;margin:0}.fc-path>svg{position:absolute;right:30px;top:30px;width:22px}.fc-footer{padding:26px 0 32px;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;font-size:12px;color:var(--muted)}.fc-footer-links{display:flex;gap:24px}.fc-footer a:hover{color:var(--green)}
        @media(max-width:800px){.fc-wrap{width:min(100% - 42px,650px)}.fc-hero{grid-template-columns:1fr;padding:63px 0 50px;gap:34px}.fc-hero h1{font-size:clamp(56px,13vw,88px)}.fc-statement{padding:70px 0}.fc-statement-inner,.fc-how-grid{grid-template-columns:1fr;gap:26px}.fc-statement h2{font-size:54px}.fc-metrics{padding:60px 0 72px}.fc-metric-grid{grid-template-columns:1fr}.fc-metric,.fc-metric+.fc-metric{min-height:0;padding:24px 0 27px;border-right:0;border-bottom:1px solid var(--line)}.fc-metric:last-child{border-bottom:0}.fc-metric h3{margin-top:18px}.fc-how{padding:70px 0}.fc-how-copy{padding-top:0}.fc-how-copy h2{max-width:none}.fc-step-cards{grid-template-columns:1fr;gap:28px;padding:16px 18px 24px}.fc-step-path{display:none}.fc-steps li{min-height:190px;padding:22px 20px}.fc-paths{padding:72px 0}.fc-home .daily-moments{padding:76px 0 80px}.fc-home .daily-moments-head{grid-template-columns:1fr;gap:22px;margin-bottom:34px}.fc-home .daily-moments h2{font-size:clamp(48px,14vw,68px)}.fc-home .daily-moments-grid{display:flex;gap:14px;overflow-x:auto;margin:0 -21px;padding:0 21px 12px;scroll-snap-type:x mandatory}.fc-home .daily-moment{flex:0 0 84vw;height:470px;scroll-snap-align:center}.fc-home .daily-moment figcaption{padding:22px}.fc-path-grid{grid-template-columns:1fr}.fc-path{min-height:220px;padding:26px}.fc-path h3{font-size:33px}.fc-footer{align-items:flex-start;gap:20px;flex-direction:column}.fc-footer-links{gap:20px}}
        @media(prefers-reduced-motion:reduce){.fc-home *{scroll-behavior:auto!important;transition:none!important}}
      `}</style>
      <CreativeDirection />
      <Navigation />
      <div className="fc-wrap">
        <section className="fc-hero" id="home">
          <div className="fc-hero-copy"><h1>Turn every delivered order into <em>next purchase.</em></h1><p>Fridge Channel puts your brand on the fridge door—visible throughout everyday household routines and ready to bring customers back with one tap.</p><a className="fc-main-cta" href="#solutions">Find the right FC solution <ArrowRight size={16} /></a></div>
          <div className="fc-hero-media"><video src="https://amzn-s3-fc-bucket.s3.sa-east-1.amazonaws.com/images/videos/hero-fridge-magnet.mp4" autoPlay muted loop playsInline aria-label="Fridge magnet rotating on a refrigerator" /></div>
        </section>
      </div>
      <section className="fc-statement"><div className="fc-wrap fc-statement-inner"><div className="fc-overline">Stay present after delivery</div><div><h2>A brand presence that lives beyond the box.</h2><p>FC turns each equipped order into a persistent, brand-controlled household touchpoint. It keeps the brand visible after the original purchase and creates a direct path from the customer&apos;s home to the brand&apos;s next selected experience.</p></div></div></section>
      <section className="fc-metrics"><div className="fc-wrap"><div className="fc-metric-grid">
        <article className="fc-metric"><h3>10+ daily family impressions</h3><p>Repeated home routines create an always-on brand surface, keeping visibility alive long after a purchase, campaign, or email send is over.</p></article>
        <article className="fc-metric"><h3>No algorithm. No ad blockers.</h3><p>No algorithm decides who sees your brand. No ad budget keeps the light on. FC is hardware-owned presence—inside the customer&apos;s home, under your control.</p></article>
        <article className="fc-metric"><h3>One tap → Next Order</h3><p>Bring customers back to your selected destination when they are ready to replenish—reducing search and shortening the path to purchase.</p></article>
      </div></div></section>
      <section className="fc-how" id="how-it-works"><div className="fc-wrap fc-how-grid"><div className="fc-how-copy"><h2>How it works</h2></div><div className="fc-step-cards"><svg className="fc-step-path" viewBox="0 0 1000 400" preserveAspectRatio="none" aria-hidden="true"><path d="M255 105 C500 105 500 105 745 105 C745 105 745 295 745 295 C745 295 500 295 255 295" /></svg><ol className="fc-steps">{steps.map((step)=><li key={step.number}><Pin /><span>{step.number}</span><span>{step.title}</span><ArrowRight /></li>)}</ol></div></div></section>
      <section className="daily-moments"><div className="fc-wrap"><div className="daily-moments-head"><div><h2>Routine moments. <em>One lasting presence.</em></h2></div><p className="daily-moments-intro">Fridge Channel lives where daily decisions already happen — naturally visible from the first coffee through the final kitchen reset.</p></div><div className="daily-moments-grid">
        <figure className="daily-moment"><Image src="/home-routine/morning-coffee.png" alt="Morning coffee preparation in a warm kitchen" fill sizes="(max-width: 800px) 84vw, 58vw" /><figcaption><span className="daily-moment-title">Morning coffee preparation</span><span className="daily-moment-number">01 / 04</span></figcaption></figure>
        <figure className="daily-moment"><Image src="/home-routine/breakfast-fridge.png" alt="Breakfast fridge visit in a family kitchen" fill sizes="(max-width: 800px) 84vw, 42vw" /><figcaption><span className="daily-moment-title">Breakfast fridge visits</span><span className="daily-moment-number">02 / 04</span></figcaption></figure>
        <figure className="daily-moment"><Image src="/home-routine/family-meal.png" alt="Family preparing a meal together" fill sizes="(max-width: 800px) 84vw, 50vw" /><figcaption><span className="daily-moment-title">Cooking and meal prep</span><span className="daily-moment-number">03 / 04</span></figcaption></figure>
        <figure className="daily-moment"><Image src="/home-routine/post-meal-cleanup.png" alt="Post-meal kitchen cleanup" fill sizes="(max-width: 800px) 84vw, 50vw" /><figcaption><span className="daily-moment-title">Post-meal cleanup and kitchen reset</span><span className="daily-moment-number">04 / 04</span></figcaption></figure>
      </div></div></section>
      <section className="fc-paths" id="solutions"><div className="fc-wrap"><div className="fc-paths-head"><h2>Choose the path that fits your business.</h2></div><div className="fc-path-grid"><Link className="fc-path" href="/who-we-serve/dtcbrands"><small>If You&apos;re a DTC Brand</small><ArrowUpRight /></Link><Link className="fc-path" href="/asin-plus"><small>If You&apos;re an Amazon Brand</small><ArrowUpRight /></Link></div></div></section>
      <footer className="fc-wrap fc-footer"><Link href="/" className="fc-brand"><Image src="/icon.svg" alt="" width={24} height={24} /><span>Fridge Channel</span></Link><div className="fc-footer-links"><Link href="/contact">Contact</Link><Link href="/trust">Trust Center</Link></div><span>© Fridge Channel</span></footer>
    </main>
  );
}
